### ISSUE TITLE
`OpenURI::HTTPError: 404 Not Found` if token doesn't have permissions.

### ISSUE THREAD

**Issue by mtpereira** [errm/slodd#1]
Hey!

I'd expect to get back a 403. This is probably some specificity of Github's API but this lib should show the appropriate error.

**Comment by errm** [comment]
Yes if you are not correctly authenticated github 404s this is reasonable becuase they don't want someone without permission to be able to enumerate things that do exist, but should be secret...

**Comment by mtpereira** [comment]
I've probably failed to explained what I meant clearly: I would expect this lib to show a cleaner, more understandable error when it 404s on Github.

`OpenURI:HTTPError: 404 Not Found` isn't as helpful as it could be: although it's pretty obvious what's happening after you read this lib's source code, it's not very friendly to force to user to do so.

It should probably have its own exception wrapping this one, with a message suggesting that either we're not authenticated/don't have enough permissions or that the repository doesn't exist.

Does that make sense? Thanks!

**Comment by errm** [comment]
Ok understood, if you want to fix this feel free ... ping me on slack and I will give you commit access.
